# Generated by Django 5.0 on 2023-12-20 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_employee_age_employee_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='compensations',
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='work_experience',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Compensation',
        ),
    ]
